version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: employee-mysql
    restart: always
    environment:
      MYSQL_DATABASE: ems
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - employee-net

  backend:
    build:
      context: "C:/Users/jnaan/Desktop/3rd Year/DevOps/project/Project/EmployeeManagementSystem/Backend/Backend/Employee-Server"
      dockerfile: "C:/Users/jnaan/Desktop/3rd Year/DevOps/project/Project/EmployeeManagementSystem/docker-git-fullstack/Dockerfile.backend"
    container_name: employee-backend
    restart: always
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/ems
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SERVER_PORT: 8081
    depends_on:
      - db
    ports:
      - "8081:8081"
    networks:
      - employee-net

  frontend:
    build:
      context: "C:/Users/jnaan/Desktop/3rd Year/DevOps/project/Project/EmployeeManagementSystem/Frontend/Frontend/employee-frontend"
      dockerfile: "C:/Users/jnaan/Desktop/3rd Year/DevOps/project/Project/EmployeeManagementSystem/docker-git-fullstack/Dockerfile.frontend"
    container_name: employee-frontend
    restart: always
    environment:
      - VITE_API_BASE_URL=http://backend:8081/ems
    ports:
      - "5173:5173"
    depends_on:
      - backend
    networks:
      - employee-net

volumes:
  db_data:

networks:
  employee-net:
    driver: bridge
