# ---------- Build stage ----------
FROM node:20-alpine AS builder
WORKDIR /app

COPY ./Frontend/Employee-Client /app

RUN npm install
RUN npm run build

# ---------- Run stage ----------
FROM nginx:alpine
WORKDIR /usr/share/nginx/html

COPY ./nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=builder /app/dist ./

EXPOSE 5173
CMD ["nginx", "-g", "daemon off;"]
