version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: employee-mysql
    restart: always
    environment:
      MYSQL_DATABASE: ems
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - employee-net
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  backend:
    build:
      context: ../Backend/Employee-Server
      dockerfile: ../docker-git-fullstackapp/Dockerfile.backend
    container_name: employee-backend
    restart: always
    depends_on:
      db:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/ems
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    ports:
      - "8081:8081"
    networks:
      - employee-net

  frontend:
    build:
      context: ../Frontend/Employee-Client
      dockerfile: ../docker-git-fullstackapp/Dockerfile.frontend
    container_name: employee-frontend
    restart: always
    depends_on:
      - backend
    ports:
      - "5173:80"
    networks:
      - employee-net

volumes:
  db_data:

networks:
  employee-net:
