name: Build Frontend and Backend

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Setup JDK for backend
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      # Step 3: Build backend (Spring Boot)
      - name: Build Spring Boot backend
        working-directory: ./backend
        run: mvn clean package -DskipTests

      # Step 4: Setup Node.js for frontend
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      # Step 5: Install and build frontend
      - name: Build React frontend
        working-directory: ./frontend
        run: |
          npm install
          npm run build

      # Step 6: Copy frontend build into backend (if serving via Spring Boot)
      - name: Copy frontend build to backend
        run: |
          mkdir -p backend/src/main/resources/static
          cp -r frontend/build/* backend/src/main/resources/static/

      # Step 7: Optional - Test combined build
      - name: Run Backend Tests
        working-directory: ./backend
        run: mvn test
