name: CI - Build & Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  backend-ci:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: ems
          MYSQL_USER: root
          MYSQL_PASSWORD: root
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 21

      - name: Build backend
        working-directory: Backend/Employee-Server
        run: ./mvnw clean package

      - name: Run backend tests
        working-directory: Backend/Employee-Server
        run: ./mvnw test

  frontend-ci:
    runs-on: ubuntu-latest
    needs: backend-ci

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        working-directory: Frontend/Employee-Client
        run: npm ci --legacy-peer-deps

      - name: Run frontend tests
        working-directory: Frontend/Employee-Client
        run: npm test --if-present

      - name: Build frontend
        working-directory: Frontend/Employee-Client
        run: npm run build
